apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloudd-dev-ingress
  namespace: cloudd-dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: cloudd-dev.cloudd-dev.tk
      http:
        paths:
          - backend:
              serviceName: cloudd-dev-svc
              servicePort: 80
