# kind: Service
# apiVersion: v1
# metadata:
#   name: ctdummylb
#   namespace: ct-dummy-dev
#   labels:
#     role: web
#     dns: route53
#   #annotations:
#     #service.beta.kubernetes.io/aws-load-balancer-internal: "false"
#     #service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: name=ct-dummy-dev, terraform=false
#     #service.beta.kubernetes.io/aws-load-balancer-type: nlb
# spec:
#   selector:
#     app: ct-dummy
#   type: LoadBalancer
#   ports:
#   - name: ui
#     port: 80
#     targetPort: 8000

apiVersion: v1
kind: Service
metadata:
  name: ct-dummy
spec:
  ports:
    - port: 80
      name: plaintext
      targetPort: 8080
  selector:
    app: ct-dummy
  type: LoadBalancer