apiVersion: apps/v1
kind: Deployment
metadata:
  name: ct-dummy
  namespace: ct-dummy-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ct-dummy
  template:
    metadata:
      labels:
        app: ct-dummy
        terraform: "false"
    spec:
      volumes:
        - name: log-pvc
          persistentVolumeClaim:
            claimName: ct-dummy-pvc
      containers:
      - name: ct-dummy
        image: klimdos/python-flask-dummy:logs
        readinessProbe:
            httpGet:
              path: /version
              port: 8000
        env:
          - name: PORT
            value: "8000"
        resources:
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /opt/logs
          name: log-pvc
