apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: ct-dummy-dev
  labels:
    app: minio
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      name: minio
  selector:
    app: minio