---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kowl-conf
  namespace: kafka-ca1
  labels:
    app: myapplication
data:
  config.yaml: |
    kafka:
      brokers:
        - kafka:9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  kowl
  namespace: kafka-ca1
  labels:
    app:  kowl
spec:
  selector:
    matchLabels:
      app: kowl
  replicas: 1
  template:
    metadata:
      labels:
        app:  kowl
    spec:
      containers:
      - name:  kowl
        image:  quay.io/cloudhut/kowl:v1.1.0
        command: ["./kowl"]
        args: ["--config.filepath=/etc/kowl/config.yaml"]
        volumeMounts:
        - name: kowl-conf-vol
          readOnly: true
          mountPath: /etc/kowl
        ports:
        - containerPort:  8080
          name:  kowl
      volumes:
        - name: kowl-conf-vol
          configMap:
            name: kowl-conf
---
kind: Service
apiVersion: v1
metadata:
  name: kowl
  namespace: kafka-ca1
spec:
  type: LoadBalancer
  selector:
    app: kowl
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
