apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: efk
  labels:
    app: kibana
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  kibana.yml: |
    # Kibana configuration for docker target
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: [ "http://elasticsearch-svc:9200" ]
    monitoring.ui.container.elasticsearch.enabled: true
